### ISSUE TITLE
ImportError: No module named 'django_google_analytics'

### ISSUE THREAD

**Issue by theparadoxer02** [clintecker/django-google-analytics#15]
I have followed all the procedure but getting this error. Here is the traceback:-
```
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7efe29fecbf8>
Traceback (most recent call last):
  File "/media/abhi/300Gb/Office/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/media/abhi/300Gb/Office/venv/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/media/abhi/300Gb/Office/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/media/abhi/300Gb/Office/venv/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/media/abhi/300Gb/Office/venv/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/media/abhi/300Gb/Office/venv/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/media/abhi/300Gb/Office/venv/lib/python3.5/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/media/abhi/300Gb/Office/venv/lib/python3.5/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/media/abhi/300Gb/Office/venv/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'django_google_analytics'
```

**Comment by niwatolli3** [comment]
me2
